version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql_banking
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend_bank
    container_name: backend_banking
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - ./backend_bank/.env
    volumes:
      - ./backend_bank:/app        # เชื่อมโฟลเดอร์ backend จากเครื่องโฮสต์ไปยัง container
      - /app/node_modules          # เชื่อม node_modules ที่ติดตั้งภายใน container
    command: npm run dev            # ใช้คำสั่ง dev เพื่อรองรับ hot-reloading

  frontend:
    build: ./frontend_bank
    container_name: frontend_banking
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://backend:5000/api
    volumes:
      - ./frontend_bank:/app       # เชื่อมโฟลเดอร์ frontend จากเครื่องโฮสต์ไปยัง container
      - /app/node_modules          # เชื่อม node_modules ที่ติดตั้งภายใน container
    command: npm start             # ใช้คำสั่ง start เพื่อรองรับ hot-reloading

volumes:
  mysql_data:
