version: "3"
services:
  db:
    image: mysql:8.0
    container_name: mysql_banking
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: banking
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: backend_banking
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev  # ใช้คำสั่งนี้แทนที่การรัน index.js
    # ที่จะให้ `npm run dev` รัน `server.js` ผ่าน `nodemon`

volumes:
  mysql_data:
